language: python
python:
#  - "2.6"
  - "2.7"
#  - "nightly"


### Whitelisting example
branches:
  only:
    - master

### Blacklisting example
#branches:
#  except:
#    - develop
#    - feature



### command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "parseLSDaltonPATH=$(pwd)"
  - "PYTHONPATH=$PYTHONPATH:$parseLSDaltonPATH"
  - "PYTHONPATH=$PYTHONPATH:${parseLSDaltonPATH}/src"
  - "PYTHONPATH=$PYTHONPATH:${parseLSDaltonPATH}/plots"
  - "PYTHONPATH=$PYTHONPATH:${parseLSDaltonPATH}/tables"
  - "echo $PYTHONPATH"
  - "export PYTHONPATH"

script:
  cd test; coverage run python -m pytest

after_success:
  coveralls