language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements.txt"
  - "PYTHONPATH=$parseLSDaltonPATH=$(pwd)"
  - "PYTHONPATH=$PYTHONPATH:$parseLSDaltonPATH"
  - "PYTHONPATH=$PYTHONPATH:${parseLSDaltonPATH}/src"
  - "PYTHONPATH=$PYTHONPATH:${parseLSDaltonPATH}/plots"
  - "PYTHONPATH=$PYTHONPATH:${parseLSDaltonPATH}/tables"

# command to run tests
script: cd test; python -m pytest